### PR TITLE
Update CartItem.php to include adjustments

### PR DESCRIPTION
**Pull request by stokic**

### CODE REVIEW

**Comment by fulopattila122** [comment]
Sorry, I can not accept this: the itemsTotal gives the items total, and only the items total, and not the items total along with the adjustments. Otherwise, how could you obtain the items total (without anything else)?

**Comment by stokic** [comment]
ok but how do you get itemsTotal with adjustments then? :) on the other hand your Cart.php has:

```
    public function total(): float
    {
        return $this->itemsTotal() + $this->adjustments()->total();
    }

```
you could argue that there total should also return just the total, without the adjustments...? 

If the adjustments are not counted in the total, when you actually apply an adjustment to CartItem all sorts of problems come up, or is there some other way the the total WITH adjustments should be used?

**Comment by fulopattila122** [comment]
One is called total the other one itemsTotal. Not a coincidence :wink:

**Comment by stokic** [comment]
I understand but I'm saying you don't have the same logic in CartItem or did I miss it somewhere? 

total() of the CartItem is this:

```
    public function total(): float
    {
        return $this->price * $this->quantity;
    }
    
    ```
    
    so again no adjustments, the question is which method can you currently call to display the price with adjustments?

**Pull request closed without merging**
